### ISSUE TITLE
Issue with the DIRECTORY.md script

### ISSUE THREAD

**Issue by dlesnoff** [TheAlgorithms/Nim#14]
@ZoomRmc proposed a script to automatically fetch the names of the different algorithms implementations.
This script does not detect the catalan_numbers.nim file in the dynamic programming directory.
I would accept any PR that partially fix these algorithm's detection issues.

**Comment by ZoomRmc** [comment]
I've checked and can't reproduce. All files are detected, including the `scripts` directory, which I'm adding to a list of ignored sub dirs in a follow-up PR.

**Comment by ZoomRmc** [comment]
Here's the output after changes made in #15:
```markdown
⚠: "dynamic_programming\catalan_numbers.nim". First line is not a doc comment! Deriving title from a file name.
⚠: "dynamic_programming\viterbi.nim". First line is not a doc comment! Deriving title from a file name.
<!--- DO NOT EDIT: This file is automatically generated by `directory.nim` -->

# The Algorithms — Nim: Directory Hierarchy

## Dynamic Programming
  * [Catalan Numbers](dynamic_programming/catalan_numbers.nim)
  * [Viterbi](dynamic_programming/viterbi.nim)

## Strings
  * [Check Anagram](strings/check_anagram.nim)
```
First two lines are written to standard error stream.

**Comment by dlesnoff** [comment]
I could not reproduce the issue on my desktop, I have to investigate this a little on my laptop.
Thank you for the PR, I will merge this tomorrow. Ping me if I forget.
