### ISSUE TITLE
Scripts directory appears on the website

### ISSUE THREAD

**Issue by dlesnoff** [TheAlgorithms/Nim#23]
https://the-algorithms.com/language/nim
The directory.nim script should not appear here, nor any future scripts.

**Comment by ZoomRmc** [comment]
Renaming to `.scripts` should suffice.
Let's push #21 and I can change it everywhere.

**Comment by dlesnoff** [comment]
Sorry it still appears. We forgot to regenerate the Directory.md file.

**Comment by ZoomRmc** [comment]
I think this is just a caching issue. The [link](https://github.com/TheAlgorithms/nim/tree/master/scripts/directory.nim) for the "Directory" solution is to the moved file.

**Comment by ZoomRmc** [comment]
Here's the script that populates the site. I'm not sure if it ignores dotted directories.
https://github.com/TheAlgorithms/website/blob/main/scripts/fetch-algorithms.ts

**Comment by dlesnoff** [comment]
This issue depends on the following website's issue: https://github.com/TheAlgorithms/website/issues/237

**Comment by Panquesito7** [comment]
Closing as this is related to the website and not this repository itself.
