### ISSUE TITLE
chore: move compiler defaults from `nim.cfg` to `config.nims`

### ISSUE THREAD

**Issue by ZoomRmc** [TheAlgorithms/Nim#26]
At this moment, in some cases setting the default `gc`/`mm` setting for the compiler results in [a compilation error](https://github.com/TheAlgorithms/Nim/pull/21#issuecomment-1574355105).
The workaround for this is moving the setting to the `nim.cfg` file. Having an additional configuration file is not great, so as soon as the fix for the bug lands in stable the setting should be moved back to the `config.nims` and `nim.cfg` should be removed.

This is a PR that sould have fixed the issue: https://github.com/nim-lang/Nim/pull/19455. Not sure why we're still hitting it.

**Comment by dlesnoff** [comment]
> Not sure why we're still hitting it.

The compilation error was obtained with Nim 1.6.12 from the post of @vil02 that you linked.
Is it still hit on Nim-devel? If so, please open an issue in the [Nim](https://github.com/Nim-lang/Nim) repository and link it here.
