### ISSUE TITLE
Change the About Section

### ISSUE THREAD

**Issue by dlesnoff** [TheAlgorithms/Nim#3]
I do not like very much the "All algorithms implemented in Nim" description. I prefer something along the lines of:
"Collection of various algorithms implemented in Nim for educational purposes." similar to the C++ repository description which is more explicit and less conceited.

We could also add a link to the documentation of the project, which will be the object of a future issue.

We might want to add more tags to the description. We can already add `educational`, `interview-questions` and more like `mathematics`, `string`,  as we add more code examples.

**Comment by Panquesito7** [comment]
Done. Thanks! 👍
