### ISSUE TITLE
The gitter link in README.md is not working.

### ISSUE THREAD

**Issue by StepfenShawn** [TheAlgorithms/Nim#39]

**Comment by dlesnoff** [comment]
Do you have any idea what would be the correct link then?
```html
  <a href="https://gitter.im/TheAlgorithms">
    <img src="https://img.shields.io/badge/Chat-Gitter-ff69b4.svg?label=Chat&logo=gitter&style=flat-square" height="20" alt="Gitter chat">
```

**Comment by StepfenShawn** [comment]
I remember it worked before, so cc the founder @AnupKumarPanwar

**Comment by dlesnoff** [comment]
Is it this one: https://app.gitter.im/#/room/#TheAlgorithms?

**Comment by StepfenShawn** [comment]
Yep, Thanks!

> Is it this one: https://app.gitter.im/#/room/#TheAlgorithms_community:gitter.im? EDIT: used another more plausible link.
