### ISSUE TITLE
[BUG] Incorrect link to the `DIRECTORY.md` file

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Nim#48]
### Description

The contributing guidelines link directly to the `DIRECTORY.md` file, to make it easier for other people to find the algorithm list.
However, the given link is incorrect and is not working, which should be immediately fixed.

_Steps to contribute_

1. Fork the repository [here](https://github.com/TheAlgorithms/Nim).
2. Create a new branch named `fix_directory_link`.
3. Open the `CONTRIBUTING.md` file.
4. Go to [line 41](https://github.com/TheAlgorithms/Nim/blob/main/CONTRIBUTING.md?plain=1#L41), and replace `directory.md` with `DIRECTORY.md`.
5. There's another instance of the same. Go to [line 52](https://github.com/TheAlgorithms/Nim/blob/main/CONTRIBUTING.md?plain=1#L52) and replace `directory.md` with `DIRECTORY.md`.
6. Commit and push your changes.
7. Create a [pull request](https://github.com/TheAlgorithms/Nim/compare) to compare your changes.
8. You're done now! 🎉 You just have to wait until the maintainers review your PR.

If you need any help with this, let us know about it. 🙂

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by ayushsgithub** [comment]
Hey, I want to solve this issue

**Comment by dlesnoff** [comment]
Some remarks on the *steps to contribute*:
- Steps 3-5 could be replaced by: sed -s s/directory.md/DIRECTORY.md/
- Create a new branch *and checkout to this new branch*
- Most importantly, write Fixes #48 in the body. That's good practice.

**Comment by ayushsgithub** [comment]
Hey @dlesnoff, I didn't understand the 1st remark, did I solved the issue?
Please explain
