### ISSUE TITLE
Add to the algorithms website

### ISSUE THREAD

**Issue by pietroppeter** [TheAlgorithms/Nim#6]
At some point we should add this to main website, for a ref PR we can see how zig was added: https://github.com/TheAlgorithms/website/pull/225/files

the only issue I see is that of highlighting, I imagine the two will not have Nim support (zig was highlighted as rust…)

**Comment by dlesnoff** [comment]
Their script is a simple typescript calling highlight.js so it depends from highlight.js syntax highlighting support.

I do not understand whether Nim is still supported by highlight.js. I do not see it in their website but it mentioned in Github pull requests and issues. See:

- https://github.com/highlightjs/highlight.js/pulls?q=is%3Apr+is%3Aclosed+nim+
- https://github.com/highlightjs/highlight.js/pull/2468

**Comment by pietroppeter** [comment]
Nim is supported by highlight.js but you need to download a version that supports Nim. This mean when we add in the PR we might need to update the highlight.js site. Anyway good news if it is like that!

**Comment by dlesnoff** [comment]
I did the PR, this is merged. Nim finally shows on the-algorithms.com !
